title: "arcologies: docs"
description: an interactive environment for designing 2d sound arcologies with norns and grid
baseurl: /arcologies-docs
url: https://northern-information.github.io/arcologies-docs
collections_dir: collections
collections:
  - structures
  - changelog
  - gallery
include: ['_pages']
